apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:2.504.1-lts-jdk21
          ports:
            - containerPort: 8080
            - containerPort: 50000
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Djavax.net.ssl.trustStore=/cacerts/cacerts -Djavax.net.ssl.trustStorePassword=changeit"
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: cacerts-volume
              mountPath: /cacerts
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pv-claim
        - name: cacerts-volume
          persistentVolumeClaim:
            claimName: cacerts-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
  ports:
    - name: jenkins
      port: 8080
      targetPort: 8080
      nodePort: 30000 # Cambia el puerto según sea necesario
    - name: jenkins-agent
      port: 50000
      targetPort: 50000
      nodePort: 30001 # Cambia el puerto según sea necesario
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # Cambia el tamaño según sea necesario
      
