pipeline {
    agent any
    
    environment {
        REPO_URL = 'https://github.com/Poswark/jenkins-test.git'
        SCRIPT_NAME = 'user.py'
    }

    parameters {
        string(name: 'NEW_USER', defaultValue: 'defaultUser', description: 'Nombre del nuevo usuario')
        string(name: 'EDAD', defaultValue: '25', description: 'Edad del nuevo usuario')
        string(name: 'NAMESPACE', defaultValue: 'defaultNamespace', description: 'Namespace del nuevo usuario')
    }

    stages {
        stage('Clone Repository') {
            steps {
                // Clonar el repositorio
                git url: "${REPO_URL}", branch: 'trunk'
            }
        }
    stage('Add Data') {
        steps {
            script {
                try {
                    // Verificar la existencia del script antes de ejecutarlo
                    if (fileExists("json-file/${SCRIPT_NAME}")) {
                        // Ejecutar el script para agregar el usuario
                        sh "python3 json-file/${SCRIPT_NAME} ${params.NEW_USER} ${params.EDAD} ${params.NAMESPACE}"
                    } else {
                        error "El script ${SCRIPT_NAME} no se encontró en la ruta json-file/"
                    }
                } catch (Exception e) {
                    error "Error ejecutando el script: ${e.getMessage()}"
                }
            }
        }
    }

        
    stage('Commit and Push Changes') {
            steps {
                script {

                   
                    // Crear y cambiar a una nueva rama
                    sh 'git checkout -b feature/add-user'
                    
                    // Agregar y hacer commit de los cambios
                    sh 'git add template.json'
                    sh 'git commit -m "Agregar nuevo usuario"'
                    
                    // Empujar la nueva rama al repositorio remoto
                    withCredentials([usernamePassword(credentialsId: 'github', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {
                        sh 'git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/Poswark/jenkins-test.git feature/add-user'
                    }
                    
                    // Crear un pull request (requiere que tengas la herramienta hub instalada o usa la API de GitHub)
                    sh 'hub pull-request -b trunk -h feature/add-user -m "Agregar nuevo usuario ${params.NEW_USER}"'
                }
            }
        }
    }
}